export const bankCodeData = [
  {
    ma_nh_dt: "ABB",
    ten_nh: "NH TMCP An Bình",
    ten_nh2: "ABBank",
    bank_code: "970425",
    citad: "01323001",
  },
  {
    ma_nh_dt: "ACB",
    ten_nh: "NH TMCP Á Châu",
    ten_nh2: "ACB",
    bank_code: "970416",
    citad: "01307001",
  },

  {
    ma_nh_dt: "BIDV",
    ten_nh: "NH TMCP Đầu tư và Phát triển VN",
    ten_nh2: "BIDV",
    bank_code: "970418",
    citad: "01202001",
  },
  {
    ma_nh_dt: "BVB",
    ten_nh: "NH TMCP Bảo Việt",
    ten_nh2: "BaoVietBank",
    bank_code: "970438",
    citad: "01359001",
  },
  {
    ma_nh_dt: "CAKE",
    ten_nh: "NH So CAKE by VPBank",
    ten_nh2: "CAKE",
    bank_code: "546034",
    citad: "",
  },
  {
    ma_nh_dt: "CBBank",
    ten_nh: "NH TM TNHH MTV Xây Dựng Việt Nam",
    ten_nh2: "CBBank",
    bank_code: "970444",
    citad: "01339001",
  },
  {
    ma_nh_dt: "CFC",
    ten_nh: "Công ty Tài chính Cổ Phần Tín Việt",
    ten_nh2: "VietCredit",
    bank_code: "970460",
    citad: "",
  },
  {
    ma_nh_dt: "CIMB",
    ten_nh: "NH TNHH MTV CIMB Việt Nam",
    ten_nh2: "CIMB",
    bank_code: "422589",
    citad: "01661001",
  },
  {
    ma_nh_dt: "COB",
    ten_nh: "NH Hợp Tác",
    ten_nh2: "Co.op Bank",
    bank_code: "970446",
    citad: "01901001",
  },
  {
    ma_nh_dt: "CTG",
    ten_nh: "NH TMCP Công Thương VN",
    ten_nh2: "VietinBank",
    bank_code: "970415",
    citad: "01201001",
  },
  {
    ma_nh_dt: "DAB",
    ten_nh: "NH TMCP Đông Á",
    ten_nh2: "DongABank",
    bank_code: "970406",
    citad: "79304001",
  },
  {
    ma_nh_dt: "DBSHCM",
    ten_nh: "NH DBS - Chi nhánh TP. HCM",
    ten_nh2: "DBS - HCM",
    bank_code: "796500",
    citad: "79650001",
  },
  {
    ma_nh_dt: "EIB",
    ten_nh: "NH TMCP Xuất Nhập Khẩu VN",
    ten_nh2: "Eximbank",
    bank_code: "970431",
    citad: "79305001",
  },
  {
    ma_nh_dt: "GPB",
    ten_nh: "NH TM TNHH MTV Dầu khí toàn cầu",
    ten_nh2: "GPBank",
    bank_code: "970408",
    citad: "79320001",
  },
  {
    ma_nh_dt: "HDB",
    ten_nh: "NH TMCP Phát triển TP HCM",
    ten_nh2: "HDBank",
    bank_code: "970437",
    citad: "79321001",
  },
  {
    ma_nh_dt: "HLB",
    ten_nh: "NH TNHH MTV Hongleong VN",
    ten_nh2: "Hongleong Bank",
    bank_code: "970442",
    citad: "79603001",
  },
  {
    ma_nh_dt: "HSBC",
    ten_nh: "NH TNHH MTV HSBC Việt Nam",
    ten_nh2: "HSBC",
    bank_code: "458761",
    citad: "79617001",
  },
  {
    ma_nh_dt: "IBKHN",
    ten_nh: "NH Công nghiệp Hàn Quốc CN Hà Nội",
    ten_nh2: "IBK - Ha Noi",
    bank_code: "970455",
    citad: "01652001",
  },
  {
    ma_nh_dt: "IVB",
    ten_nh: "NH TNHH Indovina",
    ten_nh2: "Indovina",
    bank_code: "970434",
    citad: "79502001",
  },
  {
    ma_nh_dt: "KBankHCM",
    ten_nh: "NH Đại chúng TNHH Kasikornbank - Chi nhánh TP. HCM",
    ten_nh2: "KBank - HCM",
    bank_code: "668888",
    citad: "79669001",
  },
  {
    ma_nh_dt: "KBHCM",
    ten_nh: "NH Kookmin - Chi nhánh TP. HCM",
    ten_nh2: "Kookmin - HCM",
    bank_code: "970463",
    citad: "79631001",
  },
  {
    ma_nh_dt: "KBHN",
    ten_nh: "NH Kookmin - Chi nhánh Hà Nội",
    ten_nh2: "Kookmin - HN",
    bank_code: "970462",
    citad: "01666001",
  },
  {
    ma_nh_dt: "KEBHANAHCM",
    ten_nh: "Ngân hàng Keb Hana - Chi nhánh TP Hồ Chí Minh",
    ten_nh2: "Keb Hana - Ho Chi Minh",
    bank_code: "970466",
    citad: "79656001",
  },
  {
    ma_nh_dt: "KEBHANAHN",
    ten_nh: "Ngân hàng Keb Hana - Chi nhánh Hà Nội",
    ten_nh2: "Keb Hana - Ha Noi",
    bank_code: "970467",
    citad: "01626001",
  },
  {
    ma_nh_dt: "KLB",
    ten_nh: "NH TMCP Kiên Long",
    ten_nh2: "KienLongBank",
    bank_code: "970452",
    citad: "79353001",
  },
  {
    ma_nh_dt: "LPB",
    ten_nh: "NH TMCP Bưu Điện Liên Việt",
    ten_nh2: "LienVietPostBank",
    bank_code: "970449",
    citad: "01357001",
  },
  {
    ma_nh_dt: "MAFC",
    ten_nh: "Cong ty Tai chinh TNHH MTV Mirae Asset (Việt Nam)",
    ten_nh2: "Mirae Asset",
    bank_code: "970468",
    citad: "",
  },
  {
    ma_nh_dt: "MB",
    ten_nh: "NH TMCP Quân Đội",
    ten_nh2: "MBBank",
    bank_code: "970422",
    citad: "01311001",
  },
  {
    ma_nh_dt: "MSB",
    ten_nh: "NH TMCP Hàng hải VN",
    ten_nh2: "Maritime Bank",
    bank_code: "970426",
    citad: "01302001",
  },
  {
    ma_nh_dt: "NAB",
    ten_nh: "NH TMCP Nam Á",
    ten_nh2: "NamA bank",
    bank_code: "970428",
    citad: "79306001",
  },
  {
    ma_nh_dt: "NASB",
    ten_nh: "NH TMCP Bắc Á",
    ten_nh2: "BacABank",
    bank_code: "970409",
    citad: "01313007 ",
  },
  {
    ma_nh_dt: "NCB",
    ten_nh: "Ngân hàng TMCP Quốc Dân",
    ten_nh2: "Navibank",
    bank_code: "970419",
    citad: "01352002 ",
  },
  {
    ma_nh_dt: "NonghyupBankHN",
    ten_nh: "NH Nonghyup - Chi nhánh Hà Nội",
    ten_nh2: "Nonghyup Bank - HN",
    bank_code: "801011",
    citad: "01662001",
  },
  {
    ma_nh_dt: "OCB",
    ten_nh: "NH TMCP Phương Đông",
    ten_nh2: "OCB",
    bank_code: "970448",
    citad: "79333001",
  },
  {
    ma_nh_dt: "OJB",
    ten_nh: "NH TM TNHH MTV Đại Dương",
    ten_nh2: "OceanBank",
    bank_code: "970414",
    citad: "01319001",
  },
  {
    ma_nh_dt: "PBVN",
    ten_nh: "NH TNHH MTV Public VN",
    ten_nh2: "Public bank",
    bank_code: "970439",
    citad: "01501001",
  },
  {
    ma_nh_dt: "PGB",
    ten_nh: "NH TMCP Xăng dầu Petrolimex",
    ten_nh2: "PG Bank",
    bank_code: "970430",
    citad: "01341001",
  },
  {
    ma_nh_dt: "PVCB",
    ten_nh: "NH TMCP Đại chúng VN",
    ten_nh2: "PVCombank",
    bank_code: "970412",
    citad: "01360002 ",
  },
  {
    ma_nh_dt: "SCB",
    ten_nh: "NH TMCP Sài Gòn",
    ten_nh2: "SCB",
    bank_code: "970429",
    citad: "79334001",
  },
  {
    ma_nh_dt: "SEAB",
    ten_nh: "NH TMCP Đông Nam Á",
    ten_nh2: "SeABank",
    bank_code: "970440",
    citad: "01317001",
  },
  {
    ma_nh_dt: "SGB",
    ten_nh: "NH TMCP Sài Gòn Công Thương",
    ten_nh2: "SaigonBank",
    bank_code: "970400",
    citad: "79308001",
  },
  {
    ma_nh_dt: "SHB",
    ten_nh: "NH TMCP Sài Gòn Hà Nội",
    ten_nh2: "SHB",
    bank_code: "970443",
    citad: "01348002 ",
  },
  {
    ma_nh_dt: "STANDARD",
    ten_nh: "NH TNHH MTV Standard Chartered Việt Nam",
    ten_nh2: "Standard Chartered",
    bank_code: "970410",
    citad: "01604001",
  },
  {
    ma_nh_dt: "STB",
    ten_nh: "NH TMCP Sài Gòn Thương Tín",
    ten_nh2: "Sacombank",
    bank_code: "970403",
    citad: "79303001",
  },
  {
    ma_nh_dt: "SVB",
    ten_nh: "NH TNHH MTV Shinhan VN",
    ten_nh2: "Shinhan Bank",
    bank_code: "970424",
    citad: "79616001",
  },
  {
    ma_nh_dt: "TCB",
    ten_nh: "NH TMCP Kỹ Thương VN",
    ten_nh2: "Techcombank",
    bank_code: "970407",
    citad: "01310001",
  },
  {
    ma_nh_dt: "TPB",
    ten_nh: "NH TMCP Tiên Phong",
    ten_nh2: "TPBank",
    bank_code: "970423",
    citad: "01358001",
  },
  {
    ma_nh_dt: "Ubank",
    ten_nh: "NH So Ubank by VPBank",
    ten_nh2: "Ubank",
    bank_code: "546035",
    citad: "",
  },
  {
    ma_nh_dt: "UOB",
    ten_nh: "NH TNHH MTV United Overseas Bank",
    ten_nh2: "UOB",
    bank_code: "970458",
    citad: "79618001",
  },
  {
    ma_nh_dt: "VAB",
    ten_nh: "NH TMCP Việt Á",
    ten_nh2: "VietABank",
    bank_code: "970427",
    citad: "01355002 ",
  },
  {
    ma_nh_dt: "VARB",
    ten_nh: "NH Nông Nghiệp và Phát Triển Nông Thôn Việt Nam",
    ten_nh2: "AgriBank",
    bank_code: "970405",
    citad: "01204009 ",
  },
  {
    ma_nh_dt: "VB ",
    ten_nh: "NH TMCP Việt Nam Thương Tín",
    ten_nh2: "VietBank",
    bank_code: "970433",
    citad: "79356001",
  },
  {
    ma_nh_dt: "VCB",
    ten_nh: "NH TMCP Ngoại Thương VN",
    ten_nh2: "VietcomBank",
    bank_code: "970436",
    citad: "01203001",
  },
  {
    ma_nh_dt: "VCCB",
    ten_nh: "NH TMCP Bản Việt",
    ten_nh2: "VietcapitalBank",
    bank_code: "970454",
    citad: "79327001",
  },
  {
    ma_nh_dt: "VIB",
    ten_nh: "NH TMCP Quốc Tế VN",
    ten_nh2: "VIB Bank",
    bank_code: "970441",
    citad: "01314001",
  },
  {
    ma_nh_dt: "VPB",
    ten_nh: "NH TMCP Việt Nam Thịnh Vượng",
    ten_nh2: "VPBank",
    bank_code: "970432",
    citad: "01309001",
  },
  {
    ma_nh_dt: "VRB",
    ten_nh: "NH Liên Doanh Việt Nga",
    ten_nh2: "VietNam - Russia Bank",
    bank_code: "970421",
    citad: "01505001",
  },
  {
    ma_nh_dt: "WOO",
    ten_nh: "NH Wooribank",
    ten_nh2: "Woori bank",
    bank_code: "970457",
    citad: "01663001",
  },
];
